import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';

const eslintConfig = [
  ...nextCoreWebVitals,
  {
    // firebase-messaging-sw.js is generated by scripts/generate-firebase-sw.mjs.
    ignores: ['.tmp-compare/**', 'public/firebase-messaging-sw.js'],
  },
];

export default eslintConfig;
